---
title: "R Project Day Spring 2018"
author: "Jun Seo Park"
date: "April 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading-packages}
# install.packages('tidyverse')
library(ggplot2)
library(dplyr)
```

```{r data-exploration}
station <- read.csv('GoBike_data/station.csv')
trip <- read.csv('GoBike_data/trip.csv')
str(trip)
```

```{r data-cleaning}
# Optional:
# trip$start_station_name <- as.character(trip$start_station_name)

# Try, then realize the issue:
# trip$start_date <- as.Date(trip$start_date, '%m/%d/%Y %k')
# trip$end_date <- as.Date(trip$end_date, '%m/%d/%Y %k')

# Reload the data, then:
trip$start_date <- as.character(trip$start_date)
trip$end_date <- as.character(trip$end_date)

trip$start_time <- sapply(trip$start_date, function(obs){strsplit(obs, ' ')[[1]][2]})
trip$end_time <- sapply(trip$end_date, function(obs){strsplit(obs, ' ')[[1]][2]})

trip$start_date <- as.Date(trip$start_date, '%m/%d/%Y %k')
trip$end_date <- as.Date(trip$end_date, '%m/%d/%Y %k')
```

```{r data-vis-1}
sum(trip$start_date != trip$end_date)
num_riders <- trip %>% group_by(start_date) %>% summarize(num_trips=n())
ggplot(num_riders, aes(start_date, num_trips)) + 
  geom_point()
```

```{r data-vis-2}
# Feature Engineering
num_riders <- num_riders %>% mutate('day'=weekdays(start_date, abbreviate=TRUE))
ggplot(num_riders, aes(day, num_trips)) +
  geom_bar(stat='identity')


# Reset factors to be in day order
num_riders$day <- factor(num_riders$day, levels=c('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'))
ggplot(num_riders, aes(day, num_trips)) +
  geom_bar(stat='identity')
```


```{r data-vis-3}
num_riders <- num_riders %>% mutate('weekend'=(day == 'Sat' | day == 'Sun'))
ggplot(num_riders, aes(x=start_date, y=num_trips)) +
  geom_point(aes(color = weekend))
```

```{r subscription-type}
table(trip$subscription_type)

trip_subscriptions <- trip %>% group_by(start_date, subscription_type) %>% summarize(num_trips = n())
trip_subscriptions <- trip_subscriptions %>% mutate('day'=weekdays(start_date, abbreviate=TRUE))
trip_subscriptions$day <- factor(trip_subscriptions$day, levels=c('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'))

trip_subscriptions <- trip_subscriptions %>% 
  mutate('weekend'=(day == 'Sat' | day == 'Sun'))

ggplot(trip_subscriptions, aes(x=day, y=num_trips)) +
  geom_bar(stat='identity') +
  facet_grid(subscription_type ~ .)

# Try the above first, then realize that something's up lol
# trip_subscriptions <- trip_subscriptions %>% ungroup()

ggplot(trip_subscriptions, aes(x=day, y=num_trips)) +
  geom_bar(stat='identity') +
  facet_grid(subscription_type ~ .)
```


```{r peak-times}
start_time <- strsplit(trip$start_time, ':')
convert_time <- function(obs){
  split_time <- strsplit(obs, ':')[[1]]
  hour <- as.integer(split_time[1])
  min <- as.integer(split_time[2])
  
  return(hour + min/60)
}
# Realize that the below line does not work
trip$start_time <- sapply(trip$start_time, convert_time)

ggplot(trip, aes(start_time)) +
  geom_histogram() +
  geom_vline(xintercept=9, color='red') +
  geom_vline(xintercept=17, color='red')
```

```{r distribution-of-ride-time}
trip <- trip %>% mutate('duration'=duration/60)
ggplot(trip, aes(duration)) +
  geom_histogram()
summary(trip$duration)
dim(trip %>% filter(duration > 24*60))

trip_reasonable <- trip %>% filter(duration < 24*60)
ggplot(trip_reasonable, aes(duration)) +
  geom_histogram()

trip_reasonable <- trip %>% filter(duration < 4*60)
ggplot(trip_reasonable, aes(duration)) +
  geom_histogram()

trip_reasonable <- trip %>% filter(duration < 1*60)
ggplot(trip_reasonable, aes(duration)) +
  geom_histogram()
```


```{r usage-per-city}
trip$bike_id <- as.factor(trip$bike_id)
station_cities <- station[c('id', 'name', 'city')]
trip <- left_join(trip, station_cities, by=c('start_station_id' = 'id'))

trip_cities <- trip %>% group_by(start_date, city) %>% summarize('num_trips'=n())
trip_cities <- ungroup(trip_cities)
ggplot(trip_cities, aes(start_date, num_trips)) +
  geom_point() + 
  facet_grid(city ~ .)
```



